### ISSUE TITLE
Unable to create attachment

### ISSUE THREAD

**Issue by phoney06** [johnymcreed/stylus-theme#1]
Unable to create attachment from template. The buttons are not there.
<img width="1440" alt="Screen Shot 2022-09-29 at 11 05 09 AM" src="https://user-images.githubusercontent.com/114608712/193082009-c7828e19-edca-49c4-8358-1781955894cb.png">

**Comment by johnymcreed** [comment]
found the issue regarding this. apparently i removed **mat-card-actions** which was what allowed you to edit and open these documents. Pushed: [d015b62](https://github.com/johnymcreed/stylus-theme/commit/d015b62c19f0dd2f9a465bc0e58aa2bb210bf75a)
